[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>", "Eirik Ogilvie-Wigley <eowigley@gmail.com>"]
description = "Implementation of the Jubjub elliptic curve group"
documentation = "https://docs.rs/jubjub/"
homepage = "https://github.com/zkcrypto/jubjub"
license = "MIT/Apache-2.0"
name = "jubjub"
repository = "https://github.com/zkcrypto/jubjub"
version = "0.0.0"
edition = "2018"

[dependencies.byteorder]
version = "1"
default-features = false

[dependencies.subtle]
version = "2"
default-features = false

[dependencies.rand]
version = "0.6"
default-features = false

[features]
default = ["std"]
nightly = ["subtle/nightly"]
std = ["byteorder/std", "subtle/std", "rand/std"]
